// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": [http,https],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bet/delete/{betuid}": {
            "delete": {
                "tags": ["Lottery APIs"],
                "parameters": [
                    {
                        "description": "enter a valid BetUID",
                        "name": "betuid",
                        "in": "path",
                        "required": true,
                        "type": "string",
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bet deleted successfully",
                        "schema": {
                            "type": "string",
                            "example": "Bet deleted successfully"
                        }
                    }
                }
            }
        },
        "/bet/user/{bets}": {
            "get": {
                "tags": ["Lottery APIs"],
                "parameters": [
                    {
                        "description": "enter a valid UserID",
                        "name": "bets",
                        "in": "path",
                        "required": true,
                        "type": "string",
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status ok",
                        "schema": {
                            "type": "string",
                            "example": "Status ok"
                        }
                    }
                }
            }
        },
        "/bet/history/{eventuid}": {
            "get": {
                "tags": ["Lottery APIs"],
                "parameters": [
                    {
                        "description": "enter a valid EventUID",
                        "name": "eventuid",
                        "in": "path",
                        "required": true,
                        "type": "string",
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Event history retrieved successfully",
                        "schema": {
                            "type": "string",
                            "example": "Event history retrieved successfully"
                        }
                    }
                }
            }
        },
        "/user/info/userinfo/{userid}": {
            "get": {
                "tags": ["User Information APIs"],
                "parameters": [
                    {
                        "description": "enter a valid UserID",
                        "name": "userid",
                        "in": "path",
                        "required": true,
                        "type": "string",
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User information retrieved successfully",
                        "schema": {
                            "type": "string",
                            "example": "User information retrieved successfully"
                        }
                    }
                }
            }
        },
        "/user/info/delete/{govid}": {
            "delete": {
                "tags": ["User Information APIs"],
                "parameters": [
                    {
                        "description": "enter a valid GovID",
                        "name": "govid",
                        "in": "path",
                        "required": true,
                        "type": "string",
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User information deleted successfully",
                        "schema": {
                            "type": "string",
                            "example": "User information deleted successfully"
                        }
                    }
                }
            }
        },
        "/event/eventdata": {
            "get": {
                "tags": ["Events APIs"],
                "responses": {
                    "200": {
                        "description": "Events retrieved",
                        "schema": {
                            "type": "string",
                            "example": "Events retrieved"
                        }
                    }
                }
            }
        },
        "/bet/new": {
            "post": {
                "tags": ["Lottery APIs"],
                "parameters": [
                {
                    "description": "Add new customer ",
                    "name": "info",
                    "in": "body",
                    "schema": {
                        "type": "object",
                        "properties": {
                            "UserID":{
                                "type": "string",
                                "example": "6443a1e99c150ed9e52c5bdd"
                            },
                            "EventUID": {
                                "type": "string",
                                "example": "6448e27a01d112844eaeb46d"
                            },
                            "Amount": {
                                "type": "int",
                                "example": "1000"
                            },
                            "BetNumbers": {
                                "type": "array",
                                "items": {
                                    "type": "integer"
                                },
                                "example": [1,2,3]
                            }
                        }
                    }
                }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string",
                    "example": "user info added successfully"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "My API",
	Description:      "This is Lottery Project API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
