// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": [http,https],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chat/reply/{language}": {
            "post": {
                "tags": ["Customer"],
                "parameters": [
                    {
                        "description": "eng or twi",
                        "name": "language",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "enum": ["eng", "twi"]
                    },
                {
                    "description": "Add the data",
                    "name": "select language",
                    "in": "body",
                    "schema": {
                        "type": "object",
                        "properties": {
                            "data":{
                                "type": "string",
                                "example": "hello"
                            }
                        }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "My API",
	Description:      "This is Lottery Project API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
