name: Go build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
      id: go

    - name: Add Go to PATH
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
        add-to-path: true

    - name: Install dependencies
      run: go mod tidy

    - name: Run gofmt
      run: gofmt -s -l .
      working-directory: ${{ github.workspace }}

    - name: Run goimports
      run: goimports -l -w .
      working-directory: ${{ github.workspace }}

    - name: Run golint
      run: golint ./...
      working-directory: ${{ github.workspace }}

    - name: Run tests
      run: go test -v ./...
      working-directory: ${{ github.workspace }}
